FROM eclipse-temurin:21-alpine

ADD generated/distributions/executable/launch.jar /tmp

WORKDIR /home/jgrapes-console-demo
RUN jar xf /tmp/launch.jar \
	&& rm /tmp/launch.jar

# CMD ["java","-version"]
# CMD ["bash"]

ENTRYPOINT /bin/sh start
